jobs:
  cog-tiles:
    driver: cog
    matrix:
      blocksize: [2000, 400]
      compress: [LZW, DEFLATE]
    src: s3://cloud-nes-benchmarks/ahn/4/raw/DSM05/*.TIF
    dst: s3://cloud-nes-benchmarks/ahn/4/DSM05/COG-${{ matrix.blocksize }}-${{ matrix.compress }}/
    params:
      blocksize: ${{ matrix.blocksize }}
      compress: ${{ matrix.compress }}
    overwrite: False
  cog-tiles-stac:
    driver: rio-stac
    matrix:
      blocksize: [2000, 400]
      compress: [LZW, DEFLATE]
    src: s3://cloud-nes-benchmarks/ahn/4/DSM05/COG-${{ matrix.blocksize }}-${{ matrix.compress }}/*.TIF
    dst: s3://cloud-nes-benchmarks/ahn/4/DSM05/items-${{ matrix.blocksize }}-${{ matrix.compress }}.parquet
    params:
      public_hrefs: True
      asset_media_type: 'image/tiff; application=geotiff; profile=cloud-optimized'
    overwrite: False
  cog-mosaic:
    driver: cog-mosaic
    matrix:
      blocksize: [2000, 400]
      compress: [LZW, DEFLATE]
    src: s3://cloud-nes-benchmarks/ahn/4/raw/DSM05/*.TIF
    dst: s3://cloud-nes-benchmarks/ahn/4/DSM05/COG-${{ matrix.blocksize }}-${{ matrix.compress }}-mosaic.TIF
    params:
      blocksize: ${{ matrix.blocksize }}
      compress: ${{ matrix.compress }}
    overwrite: False
  vrt-cog-tiles:
    driver: vrt
    matrix:
      blocksize: [2000, 400]
      compress: [LZW, DEFLATE]
    src: s3://cloud-nes-benchmarks/ahn/4/DSM05/COG-${{ matrix.blocksize }}-${{ matrix.compress }}/*.TIF
    dst: s3://cloud-nes-benchmarks/ahn/4/DSM05/VRT-${{ matrix.blocksize }}-${{ matrix.compress }}-mosaic.VRT
    params:
      blocksize: ${{ matrix.blocksize }}
      compress: ${{ matrix.compress }}
    overwrite: False
