jobs:
  cog-tiles:
    driver: cog
    src: s3://cloud-nes-benchmarks/bm-hrl/2024O/raw/RGB/*.tif
    dst: s3://cloud-nes-benchmarks/bm-hrl/2024O/RGB/COG-512-LZW/
    params:
      blocksize: 512
      compress: LZW
    overwrite: False
  cog-tiles-stac:
    driver: rio-stac
    src: s3://cloud-nes-benchmarks/bm-hrl/2024O/RGB/COG-512-LZW/*.tif
    dst: s3://cloud-nes-benchmarks/bm-hrl/2024O/RGB/items-COG-512-LZW.parquet
    params:
      public_hrefs: True
      asset_media_type: 'image/tiff; application=geotiff; profile=cloud-optimized'
    overwrite: False
  vrt-cog-tiles:
    driver: vrt
    src: s3://cloud-nes-benchmarks/bm-hrl/2024O/RGB/COG-512-LZW/*.tif
    dst: s3://cloud-nes-benchmarks/bm-hrl/2024O/RGB/VRT-512-LZW-mosaic.VRT
    overwrite: False
  cog-mosaic:
    driver: cog-mosaic
    src: s3://cloud-nes-benchmarks/bm-hrl/2024O/RGB/COG-512-LZW/*.tif
    dst: s3://cloud-nes-benchmarks/bm-hrl/2024O/RGB/COG-512-LZW-mosaic.tif
    params:
      blocksize: 512
      compress: LZW
      bigtiff: YES
    overwrite: False

